# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('input_gene', models.TextField()),
                ('input_phenotype', models.TextField()),
                ('result', models.TextField()),
                ('pub_date', models.DateTimeField()),
                ('user_name', models.CharField(max_length=10)),
                ('take_name', models.CharField(max_length=20)),
            ],
        ),
    ]
