# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_input_table',
            name='status',
            field=models.CharField(default='', max_length=40),
        ),
    ]
