# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main_table',
            old_name='result_table',
            new_name='result',
        ),
    ]
