# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table',
            name='input_gene',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main_table',
            name='input_phenotype',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main_table',
            name='result_table',
            field=models.TextField(),
        ),
    ]
