# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0002_raw_input_table_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raw_input_table',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
