# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0003_auto_20170508_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='interpretation',
            field=models.TextField(default=''),
        ),
    ]
