# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0003_auto_20170422_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_table',
            name='input_gene',
            field=models.CharField(max_length=20000),
        ),
    ]
