# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0003_raw_input_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='raw_input_table',
            name='task_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='raw_input_table',
            name='user_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
