# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0004_main_table_interpretation'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_table',
            name='interpretation_chinese',
            field=models.TextField(default=''),
        ),
    ]
