# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0005_auto_20170422_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main_table',
            name='input_gene',
        ),
        migrations.RemoveField(
            model_name='main_table',
            name='input_phenotype',
        ),
        migrations.RemoveField(
            model_name='main_table',
            name='result_table',
        ),
    ]
