# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0006_auto_20170422_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.IntegerField(default=0)),
                ('input_gene', models.CharField(max_length=300)),
                ('input_phenotype', models.CharField(max_length=100)),
                ('result_table', models.CharField(max_length=120)),
                ('pub_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='main_table',
        ),
    ]
