# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepb', '0007_auto_20170422_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='input_gene',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='input_phenotype',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='result_table',
            field=models.TextField(),
        ),
    ]
